<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <actionOverrides>
        <actionName>View</actionName>
        <comment>Action override created by Lightning App Builder during activation.</comment>
        <content>Opportunity_Record_Page1</content>
        <formFactor>Large</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
        <pageOrSobjectType>Opportunity</pageOrSobjectType>
    </actionOverrides>
    <formFactors>Large</formFactors>
    <label>LightningService</label>
    <navType>Console</navType>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Account_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Account</pageOrSobjectType>
        <recordType>PersonAccount.PersonAccount</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <setupExperience>service</setupExperience>
    <tab>standard-Case</tab>
    <tab>standard-Contact</tab>
    <tab>standard-Account</tab>
    <tab>standard-report</tab>
    <tab>standard-Dashboard</tab>
    <tab>standard-home</tab>
    <uiType>Lightning</uiType>
    <utilityBar>LightningService_UtilityBar</utilityBar>
    <workspaceMappings>
        <mapping>
            <tab>standard-Account</tab>
        </mapping>
        <mapping>
            <tab>standard-Case</tab>
        </mapping>
        <mapping>
            <tab>standard-Contact</tab>
        </mapping>
        <mapping>
            <tab>standard-Dashboard</tab>
        </mapping>
        <mapping>
            <tab>standard-home</tab>
        </mapping>
        <mapping>
            <tab>standard-report</tab>
        </mapping>
    </workspaceMappings>
</CustomApplication>
