public  class TW1_Ancar_wrapRecodtypes {
    public String rec_loja 		= 'Oportunidade de Loja';
    public String rec_feiras 	= 'Oportunidade de Feiras e Eventos';
    public String rec_mall 		= 'Oportunidade de Mall';
    public String rec_midia 	= 'Oportunidade de Mídia';
    
    public String rec_Cotcao_loja 	= 'Cotação de Loja';
    public String rec_Cotcao_mall 	= 'Cotação de Mall';
    public String rec_Cotcao_midia 	= 'Cotação de Mídia';
    public String rec_Cotcao_feiras = 'Cotação de Feiras e Eventos';
    
    public String rec_Prop_Feiras = 'Propriedade feiras e eventos';
    public String rec_Prop_Loja = 'Propriedade de loja';
    public String rec_Prop_Mall = 'Propriedade de mall';
    public String rec_Prop_Midia = 'Propriedade de mídia';
    
    public String rec_Marca = 'Marca';
    public String rec_Contato_Comercial_PF = 'Contato comercial PF';
    
    public String rec_ProfileAdmin = 'System Administrator';
}